"use client";

import Link from "next/link";
import { use, useEffect, useState } from "react";
import { ArrowLeft, FileText, Image as ImageIcon, RefreshCw, Trash2, Upload } from "lucide-react";
import { EmptyState, InlineAlert, MetricCard, Panel } from "@/components/dashboard/premium-ui";

type Doc={id:string;file_name:string;storage_url:string;content_type:string;size_bytes:number;category:string;visibility:string;version:number;created_at:string;uploaded_by:{id:string;name:string|null;email:string}};
type Data={documents:Doc[];canManage:boolean};
const dt=new Intl.DateTimeFormat("sv-SE",{dateStyle:"medium",timeStyle:"short"});
const categories=[['before','Före-bild'],['after','Efter-bild'],['invoice','Faktura'],['warranty','Garanti'],['manual','Manual'],['report','Rapport'],['other','Övrigt']];
const labels=Object.fromEntries(categories);
const input='w-full rounded-xl border border-sand-200 bg-white px-3 py-2.5 text-sm text-ink-900 outline-none focus:border-petroleum-500';
function size(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1048576)return `${(bytes/1024).toFixed(1)} kB`;return `${(bytes/1048576).toFixed(1)} MB`;}

export default function WorkOrderDocumentsPage({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const [data,setData]=useState<Data|null>(null);const [file,setFile]=useState<File|null>(null);const [category,setCategory]=useState('before');const [visibility,setVisibility]=useState('internal');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch(`/api/work-orders/${id}/documents`,{cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error||'Kunde inte hämta dokument');setData(b);}catch(e){setError(e instanceof Error?e.message:'Kunde inte hämta dokument');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[id]);
 async function upload(){if(!file)return;setBusy(true);setError('');setMessage('');try{const form=new FormData();form.set('file',file);form.set('category',category);form.set('visibility',visibility);const r=await fetch(`/api/work-orders/${id}/documents`,{method:'POST',body:form});const b=await r.json();if(!r.ok)throw new Error(b.error||'Kunde inte ladda upp filen');setFile(null);setMessage('Dokumentet har laddats upp.');await load();}catch(e){setError(e instanceof Error?e.message:'Kunde inte ladda upp filen');}finally{setBusy(false);}}
 async function remove(documentId:string){if(!confirm('Ta bort dokumentet permanent?'))return;setBusy(true);setError('');try{const r=await fetch(`/api/work-orders/${id}/documents?documentId=${encodeURIComponent(documentId)}`,{method:'DELETE'});const b=await r.json();if(!r.ok)throw new Error(b.error||'Kunde inte ta bort dokumentet');await load();}catch(e){setError(e instanceof Error?e.message:'Kunde inte ta bort dokumentet');}finally{setBusy(false);}}
 const docs=data?.documents||[];const images=docs.filter(d=>d.content_type.startsWith('image/')).length;const pdfs=docs.filter(d=>d.content_type==='application/pdf').length;
 return <div className="mx-auto max-w-7xl space-y-6 animate-fade-in-soft">
  <header className="rounded-2xl border border-sand-200 bg-white p-7 shadow-premium-sm"><Link href={`/dashboard/arbetsordrar/${id}`} className="inline-flex items-center gap-2 text-sm font-semibold text-petroleum-700"><ArrowLeft className="h-4 w-4"/>Till arbetsordern</Link><div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-petroleum-600">Dokumentation</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-ink-950">Arbetsorderdokument</h1><p className="mt-2 text-ink-600">Samla före-/efterbilder, PDF-rapporter, garantier och underlag.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-sand-200 px-4 py-2.5 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Uppdatera</button></div></header>
  {error?<InlineAlert>{error}</InlineAlert>:null}{message?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-800">{message}</div>:null}
  <div className="grid gap-4 sm:grid-cols-3"><MetricCard icon={FileText} label="Dokument" value={docs.length}/><MetricCard icon={ImageIcon} label="Bilder" value={images}/><MetricCard icon={FileText} label="PDF" value={pdfs}/></div>
  {data?.canManage?<Panel title="Ladda upp dokument" description="Tillåtna format: JPG, PNG, WebP och PDF. Max 15 MB per fil."><div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_220px_180px_auto] md:items-end"><label className="text-sm font-semibold">Fil<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className={`${input} mt-1.5`} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label className="text-sm font-semibold">Kategori<select className={`${input} mt-1.5`} value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-sm font-semibold">Synlighet<select className={`${input} mt-1.5`} value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="internal">Intern</option><option value="shared">Delad</option></select></label><button onClick={()=>void upload()} disabled={busy||!file} className="inline-flex items-center justify-center gap-2 rounded-xl bg-petroleum-800 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Upload className="h-4 w-4"/>{busy?'Laddar…':'Ladda upp'}</button></div></Panel>:null}
  <Panel title="Dokumentarkiv" description="Alla dokument är kopplade till denna arbetsorder och organisation.">{loading&&!data?<div className="h-48 animate-pulse rounded-xl bg-sand-100"/>:null}{!loading&&!docs.length?<EmptyState title="Inga dokument ännu" description="Ladda upp det första dokumentet för arbetsordern."/>:null}{docs.length?<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{docs.map(doc=><article key={doc.id} className="overflow-hidden rounded-xl border border-sand-200 bg-white">{doc.content_type.startsWith('image/')?<a href={doc.storage_url} target="_blank" rel="noreferrer"><img src={doc.storage_url} alt={doc.file_name} className="h-44 w-full object-cover"/></a>:<a href={doc.storage_url} target="_blank" rel="noreferrer" className="flex h-44 items-center justify-center bg-sand-50"><FileText className="h-12 w-12 text-petroleum-700"/></a>}<div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><a href={doc.storage_url} target="_blank" rel="noreferrer" className="block truncate font-semibold text-ink-950 hover:text-petroleum-700">{doc.file_name}</a><p className="mt-1 text-xs text-ink-500">{labels[doc.category]||doc.category} · {size(doc.size_bytes)} · {doc.visibility==='shared'?'Delad':'Intern'}</p></div>{data?.canManage?<button onClick={()=>void remove(doc.id)} disabled={busy} className="rounded-lg p-2 text-red-600 hover:bg-red-50" aria-label="Ta bort dokument"><Trash2 className="h-4 w-4"/></button>:null}</div><p className="mt-3 text-xs text-ink-500">{doc.uploaded_by.name||doc.uploaded_by.email} · {dt.format(new Date(doc.created_at))}</p></div></article>)}</div>:null}</Panel>
 </div>;
}
