"use client";

import Link from "next/link";
import { use, useCallback, useEffect, useState } from "react";
import { ArrowLeft, Clock3, MessageSquare, RefreshCw, Save, UserRound, Wrench } from "lucide-react";
import { InlineAlert, MetricCard, Panel } from "@/components/dashboard/premium-ui";

type Person={id:string;name:string|null;email:string;role?:string};
type Comment={id:string;body:string;is_internal:boolean;created_at:string;user:Person};
type History={id:string;action:string;metadata:unknown;created_at:string;actor:Person|null};
type Order={id:string;title:string;description:string;status:string;priority:string;assigned_to_id:string|null;scheduled_start:string|null;scheduled_end:string|null;estimated_cost:string|null;actual_cost:string|null;created_at:string;updated_at:string;completed_at:string|null;property:{name:string;address:string;city:string};unit:{designation:string}|null;ticket:{id:string;public_reference:string|null;title:string}|null;assigned_to:Person|null;created_by:Person;projects:{id:string;name:string;status:string}[]};
type Form={title:string;description:string;status:string;priority:string;assignedToId:string;scheduledStart:string;scheduledEnd:string;estimatedCost:string;actualCost:string};
const statuses=[['new','Ny'],['planned','Planerad'],['in_progress','Påbörjad'],['waiting_material','Väntar material'],['blocked','Blockerad'],['completed','Klar'],['invoiced','Fakturerad'],['cancelled','Avbruten']];
const priorities=[['low','Låg'],['normal','Normal'],['high','Hög'],['urgent','Akut']];
const dt=new Intl.DateTimeFormat('sv-SE',{dateStyle:'medium',timeStyle:'short'});
const input='w-full rounded-xl border border-sand-200 bg-white px-3 py-2.5 text-sm text-ink-900 outline-none focus:border-petroleum-500';
function local(value:string|null){if(!value)return '';const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}

export default function WorkOrderDetailPage({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const [order,setOrder]=useState<Order|null>(null);const [users,setUsers]=useState<Person[]>([]);const [form,setForm]=useState<Form|null>(null);const [comments,setComments]=useState<Comment[]>([]);const [history,setHistory]=useState<History[]>([]);const [comment,setComment]=useState('');const [canManage,setCanManage]=useState(false);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [a,b]=await Promise.all([fetch(`/api/work-orders/${id}`,{cache:'no-store'}),fetch(`/api/work-orders/${id}/comments`,{cache:'no-store'})]);const x=await a.json(),y=await b.json();if(!a.ok)throw new Error(x.error||'Kunde inte hämta arbetsordern');if(!b.ok)throw new Error(y.error||'Kunde inte hämta historiken');setOrder(x.workOrder);setUsers(x.users||[]);setCanManage(Boolean(x.canManage));setComments(y.comments||[]);setHistory(y.history||[]);const o=x.workOrder;setForm({title:o.title,description:o.description,status:o.status,priority:o.priority,assignedToId:o.assigned_to_id||'',scheduledStart:local(o.scheduled_start),scheduledEnd:local(o.scheduled_end),estimatedCost:o.estimated_cost||'',actualCost:o.actual_cost||''});}catch(e){setError(e instanceof Error?e.message:'Ett fel uppstod');}finally{setLoading(false);}},[id]);
 useEffect(()=>{void load();},[load]);
 async function save(){if(!form)return;setSaving(true);setError('');setMessage('');try{const r=await fetch(`/api/work-orders/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const b=await r.json();if(!r.ok)throw new Error(b.error||'Kunde inte spara arbetsordern');setMessage('Arbetsordern har sparats.');await load();}catch(e){setError(e instanceof Error?e.message:'Kunde inte spara');}finally{setSaving(false);}}
 async function addComment(){const text=comment.trim();if(!text)return;setSaving(true);setError('');try{const r=await fetch(`/api/work-orders/${id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body:text,isInternal:true})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Kunde inte lägga till kommentaren');setComment('');await load();}catch(e){setError(e instanceof Error?e.message:'Kunde inte lägga till kommentaren');}finally{setSaving(false);}}
 if(loading&&!order)return <div className="h-72 animate-pulse rounded-2xl bg-sand-100"/>;if(!order||!form)return <InlineAlert>{error||'Arbetsordern kunde inte visas.'}</InlineAlert>;
 const set=(key:keyof Form,value:string)=>setForm({...form,[key]:value});
 return <div className="mx-auto max-w-7xl space-y-6 animate-fade-in-soft">
  <header className="rounded-2xl border border-sand-200 bg-white p-7 shadow-premium-sm"><Link href="/dashboard/arbetsordrar/operationsoversikt" className="inline-flex items-center gap-2 text-sm font-semibold text-petroleum-700"><ArrowLeft className="h-4 w-4"/>Arbetsorderöversikt</Link><div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-petroleum-600">Arbetsorder</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-ink-950">{order.title}</h1><p className="mt-2 text-ink-600">{order.property.name} · {order.property.address}, {order.property.city}{order.unit?` · ${order.unit.designation}`:''}</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-sand-200 px-4 py-2.5 text-sm font-semibold"><RefreshCw className="h-4 w-4"/>Uppdatera</button></div></header>
  {error?<InlineAlert>{error}</InlineAlert>:null}{message?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-800">{message}</div>:null}
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><MetricCard icon={Wrench} label="Status" value={statuses.find(x=>x[0]===order.status)?.[1]||order.status}/><MetricCard icon={Clock3} label="Planerad start" value={order.scheduled_start?dt.format(new Date(order.scheduled_start)):'Ej planerad'}/><MetricCard icon={UserRound} label="Ansvarig" value={order.assigned_to?.name||order.assigned_to?.email||'Ej tilldelad'}/><MetricCard icon={MessageSquare} label="Kommentarer" value={comments.length}/></div>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(340px,.8fr)]"><Panel title="Arbetsorderuppgifter" description="Status, ansvar, planering och ekonomi."><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-semibold">Rubrik<input className={`${input} mt-1.5`} value={form.title} disabled={!canManage} onChange={e=>set('title',e.target.value)}/></label><label className="sm:col-span-2 text-sm font-semibold">Beskrivning<textarea className={`${input} mt-1.5 min-h-32`} value={form.description} disabled={!canManage} onChange={e=>set('description',e.target.value)}/></label><label className="text-sm font-semibold">Status<select className={`${input} mt-1.5`} value={form.status} disabled={!canManage} onChange={e=>set('status',e.target.value)}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="text-sm font-semibold">Prioritet<select className={`${input} mt-1.5`} value={form.priority} disabled={!canManage} onChange={e=>set('priority',e.target.value)}>{priorities.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="sm:col-span-2 text-sm font-semibold">Ansvarig<select className={`${input} mt-1.5`} value={form.assignedToId} disabled={!canManage} onChange={e=>set('assignedToId',e.target.value)}><option value="">Ej tilldelad</option>{users.map(u=><option key={u.id} value={u.id}>{u.name||u.email} · {u.role||''}</option>)}</select></label><label className="text-sm font-semibold">Planerad start<input type="datetime-local" className={`${input} mt-1.5`} value={form.scheduledStart} disabled={!canManage} onChange={e=>set('scheduledStart',e.target.value)}/></label><label className="text-sm font-semibold">Planerat slut<input type="datetime-local" className={`${input} mt-1.5`} value={form.scheduledEnd} disabled={!canManage} onChange={e=>set('scheduledEnd',e.target.value)}/></label><label className="text-sm font-semibold">Beräknad kostnad<input type="number" min="0" step="0.01" className={`${input} mt-1.5`} value={form.estimatedCost} disabled={!canManage} onChange={e=>set('estimatedCost',e.target.value)}/></label><label className="text-sm font-semibold">Faktisk kostnad<input type="number" min="0" step="0.01" className={`${input} mt-1.5`} value={form.actualCost} disabled={!canManage} onChange={e=>set('actualCost',e.target.value)}/></label></div>{canManage?<div className="mt-5 flex justify-end"><button onClick={()=>void save()} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-petroleum-800 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Sparar…':'Spara ändringar'}</button></div>:<p className="mt-4 text-sm text-ink-500">Du har läsbehörighet men kan inte ändra arbetsordern.</p>}</Panel>
  <div className="space-y-6"><Panel title="Kommentarer" description="Intern operativ dialog."><div className="space-y-3">{comments.map(c=><div key={c.id} className="rounded-xl border border-sand-200 p-4"><p className="text-sm text-ink-800">{c.body}</p><p className="mt-2 text-xs text-ink-500">{c.user.name||c.user.email} · {dt.format(new Date(c.created_at))}</p></div>)}{!comments.length?<p className="text-sm text-ink-500">Inga kommentarer ännu.</p>:null}</div>{canManage?<div className="mt-4"><textarea className={`${input} min-h-24`} placeholder="Skriv en intern kommentar…" value={comment} onChange={e=>setComment(e.target.value)}/><button onClick={()=>void addComment()} disabled={saving||!comment.trim()} className="mt-2 rounded-xl bg-petroleum-800 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Lägg till kommentar</button></div>:null}</Panel><Panel title="Revisionshistorik" description="Registrerade ändringar och åtgärder."><div className="space-y-3">{history.map(h=><div key={h.id} className="border-l-2 border-petroleum-200 pl-3"><p className="text-sm font-semibold text-ink-800">{h.action}</p><p className="text-xs text-ink-500">{h.actor?.name||h.actor?.email||'System'} · {dt.format(new Date(h.created_at))}</p></div>)}{!history.length?<p className="text-sm text-ink-500">Ingen historik registrerad ännu.</p>:null}</div></Panel></div></div>
 </div>;
}
