"use client";

import Link from "next/link";
import { use, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, PauseCircle, Play, RefreshCw, Route, Save, Square, TimerReset } from "lucide-react";
import { EmptyState, InlineAlert, MetricCard, Panel } from "@/components/dashboard/premium-ui";

type Entry = { entryId:string; userId:string; userName?:string|null; userEmail:string; kind:"work"|"travel"|"break"; startedAt?:string|null; endedAt?:string|null; minutes?:number|null; billable?:boolean; note?:string|null; status?:"running"|"submitted"|"approved"|"rejected"; createdAt:string };
type Data = { entries:Entry[]; summary:{work:number;travel:number;break:number;billable:number;running:number;pending:number}; canManage:boolean };
const dt=new Intl.DateTimeFormat("sv-SE",{dateStyle:"medium",timeStyle:"short"});
const input="w-full rounded-xl border border-sand-200 bg-white px-3 py-2.5 text-sm text-ink-900 outline-none focus:border-petroleum-500";
const labels={work:"Arbetstid",travel:"Restid",break:"Rast"};
function duration(minutes:number){const h=Math.floor(minutes/60),m=minutes%60;return h?`${h} h ${m} min`:`${m} min`;}
function localNow(offsetMinutes=0){const d=new Date(Date.now()+offsetMinutes*60000);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}

export default function WorkOrderTimePage({params}:{params:Promise<{id:string}>}){
 const {id}=use(params);const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
 const [form,setForm]=useState({kind:"work",startedAt:localNow(-60),endedAt:localNow(),billable:true,note:""});
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/work-orders/${id}/time-entries`,{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error||"Kunde inte hämta tidsrapporteringen");setData(b);}catch(e){setError(e instanceof Error?e.message:"Kunde inte hämta tidsrapporteringen");}finally{setLoading(false);}},[id]);
 useEffect(()=>{void load();},[load]);
 async function action(payload:Record<string,unknown>){setSaving(true);setError("");setMessage("");try{const r=await fetch(`/api/work-orders/${id}/time-entries`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Åtgärden misslyckades");setMessage("Tidsrapporteringen har uppdaterats.");setForm({...form,note:""});await load();}catch(e){setError(e instanceof Error?e.message:"Åtgärden misslyckades");}finally{setSaving(false);}}
 const rows=data?.entries??[];const running=rows.filter(x=>x.status==="running");const totals=useMemo(()=>data?.summary??{work:0,travel:0,break:0,billable:0,running:0,pending:0},[data]);
 return <div className="mx-auto max-w-7xl space-y-6 animate-fade-in-soft">
  <header className="rounded-2xl border border-sand-200 bg-white p-7 shadow-premium-sm"><Link href={`/dashboard/arbetsordrar/${id}`} className="inline-flex items-center gap-2 text-sm font-semibold text-petroleum-700"><ArrowLeft className="h-4 w-4"/>Till arbetsordern</Link><div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-petroleum-600">Arbetsorder</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-ink-950">Tidsrapportering</h1><p className="mt-2 text-ink-600">Registrera arbetstid, restid, raster och debiterbar tid med full spårbarhet.</p></div><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-sand-200 px-4 py-2.5 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>Uppdatera</button></div></header>
  {error?<InlineAlert>{error}</InlineAlert>:null}{message?<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-800">{message}</div>:null}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><MetricCard icon={Clock3} label="Arbetstid" value={duration(totals.work)}/><MetricCard icon={Route} label="Restid" value={duration(totals.travel)}/><MetricCard icon={PauseCircle} label="Raster" value={duration(totals.break)}/><MetricCard icon={CheckCircle2} label="Debiterbart" value={duration(totals.billable)}/><MetricCard icon={Play} label="Aktiva timers" value={totals.running}/><MetricCard icon={TimerReset} label="Väntar attest" value={totals.pending}/></div>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(340px,.8fr)]">
   <Panel title="Tidsposter" description="Alla registreringar för arbetsordern.">{loading&&!data?<div className="h-52 animate-pulse rounded-xl bg-sand-100"/>:null}{!loading&&!rows.length?<EmptyState title="Ingen tid registrerad" description="Starta en timer eller skapa en manuell tidsrad."/>:null}<div className="space-y-3">{rows.map(row=><div key={row.entryId} className="rounded-xl border border-sand-200 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-ink-900">{labels[row.kind]}</p><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${row.status==="approved"?"bg-emerald-50 text-emerald-800":row.status==="rejected"?"bg-red-50 text-red-700":row.status==="running"?"bg-blue-50 text-blue-700":"bg-amber-50 text-amber-800"}`}>{row.status==="approved"?"Attesterad":row.status==="rejected"?"Avvisad":row.status==="running"?"Pågår":"Väntar attest"}</span>{row.billable&&row.kind!=="break"?<span className="rounded-full bg-petroleum-50 px-2.5 py-1 text-xs font-semibold text-petroleum-800">Debiterbar</span>:null}</div><p className="mt-1 text-sm text-ink-500">{row.userName||row.userEmail}{row.startedAt?` · ${dt.format(new Date(row.startedAt))}`:""}{row.endedAt?` – ${dt.format(new Date(row.endedAt))}`:""}</p>{row.note?<p className="mt-2 text-sm text-ink-700">{row.note}</p>:null}</div><div className="flex items-center gap-2"><p className="min-w-20 text-right font-semibold text-ink-900">{row.minutes?duration(row.minutes):row.status==="running"?"Pågår":"0 min"}</p>{row.status==="running"?<button onClick={()=>void action({action:"stop",entryId:row.entryId,kind:row.kind})} disabled={saving} className="inline-flex items-center gap-1.5 rounded-lg bg-ink-900 px-3 py-2 text-xs font-semibold text-white"><Square className="h-3.5 w-3.5"/>Stoppa</button>:null}{data?.canManage&&row.status==="submitted"?<><button onClick={()=>void action({action:"approve",entryId:row.entryId,kind:row.kind})} disabled={saving} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-semibold text-white">Attestera</button><button onClick={()=>void action({action:"reject",entryId:row.entryId,kind:row.kind})} disabled={saving} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700">Avvisa</button></>:null}</div></div></div>)}</div></Panel>
   <div className="space-y-6"><Panel title="Starta timer" description="Startar omedelbart för inloggad användare."><div className="grid gap-3"><select className={input} value={form.kind} onChange={e=>setForm({...form,kind:e.target.value,billable:e.target.value!=="break"})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><textarea className={`${input} min-h-24`} placeholder="Kommentar eller utförd åtgärd" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><label className="flex items-center gap-2 text-sm text-ink-700"><input type="checkbox" checked={form.billable} disabled={form.kind==="break"} onChange={e=>setForm({...form,billable:e.target.checked})}/>Debiterbar tid</label><button onClick={()=>void action({action:"start",kind:form.kind,billable:form.billable,note:form.note})} disabled={saving||running.length>0} className="inline-flex items-center justify-center gap-2 rounded-xl bg-petroleum-800 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Play className="h-4 w-4"/>{running.length?"En timer pågår redan":"Starta timer"}</button></div></Panel>
   <Panel title="Manuell tidsrad" description="För efterregistrering och korrigering."><div className="grid gap-3"><select className={input} value={form.kind} onChange={e=>setForm({...form,kind:e.target.value,billable:e.target.value!=="break"})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><label className="text-sm font-semibold text-ink-800">Start<input type="datetime-local" className={`${input} mt-1.5`} value={form.startedAt} onChange={e=>setForm({...form,startedAt:e.target.value})}/></label><label className="text-sm font-semibold text-ink-800">Slut<input type="datetime-local" className={`${input} mt-1.5`} value={form.endedAt} onChange={e=>setForm({...form,endedAt:e.target.value})}/></label><textarea className={`${input} min-h-20`} placeholder="Kommentar" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><label className="flex items-center gap-2 text-sm text-ink-700"><input type="checkbox" checked={form.billable} disabled={form.kind==="break"} onChange={e=>setForm({...form,billable:e.target.checked})}/>Debiterbar tid</label><button onClick={()=>void action({action:"manual",...form})} disabled={saving} className="inline-flex items-center justify-center gap-2 rounded-xl bg-petroleum-800 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4"/>Spara tidsrad</button></div></Panel></div>
  </div>
 </div>;
}
